### ISSUE TITLE
请问能发我一份您所做的predoo论文吗？

### ISSUE THREAD

**Issue by Zoeeeeey** [predoodl/predoo#1]
您好！我想看一下您的论文，但是IEEE上需要付费，请问您能不能给我发一份，或者有没有什么不需要付费的下载路径呢？谢谢！！！

**Comment by sunshinezxf** [comment]
你好，不好意思这么晚了回复。论文可以从[链接](http://pub.zhangxufan.cn) 上下载，或者您发电子邮件给我，xufan.zhang@outlook.com，我把论文发给你。感谢对我们工作的关注！

**Comment by Zoeeeeey** [comment]
好的，谢谢！我已经从链接中获取了 ~~
